# Use an existing docker image as base
FROM alpine
# Donwload and install dependncy
RUN apk add --update gcc
RUN apk add --update redis

# Tell the image what to do when it starts the image
CMD ["redis-server"]